export const compactScrollableCardClassName = "flex min-h-0 flex-1 overflow-hidden"
export const tallScrollableCardClassName = "flex min-h-0 flex-1 overflow-hidden"
export const wideScrollableCardClassName = "flex min-h-0 flex-1 overflow-hidden"

export const analyticsGridClassName = "grid gap-6 lg:grid-cols-2 xl:grid-cols-12 xl:auto-rows-[336px]"
export const analyticsPanelColumnClassName = "min-h-0 xl:col-span-4 xl:h-full"
export const analyticsPanelCardClassName = "flex min-h-0 h-full flex-1 flex-col gap-0 overflow-hidden border-border py-0 shadow-sm"
export const analyticsPanelHeaderClassName = "flex min-h-[104px] flex-col justify-start gap-1 px-5 pb-3 pt-4 sm:min-h-[96px]"
export const analyticsPanelDescriptionClassName = "max-w-full break-words text-xs leading-5 text-muted-foreground"
export const nestedMetricGridClassName = "grid w-full grid-cols-2 content-start gap-2"
export const nestedMetricTileClassName = "flex min-h-[84px] flex-col justify-between rounded-lg border border-border bg-muted/30 px-3 py-2.5"
export const nestedMetricLabelClassName = "min-h-[2.25rem] break-words text-[11px] leading-4 text-muted-foreground"
export const dashboardGridClassName = "grid gap-6 xl:grid-cols-12 xl:auto-rows-[420px]"
export const dashboardMonitoringCardClassName = "flex min-h-0 h-full flex-col gap-0 overflow-hidden border-border py-0 shadow-sm"
export const dashboardMonitoringHeaderClassName = "flex min-h-[96px] flex-col items-start px-5 pb-3 pt-5"
export const dashboardInsightGridClassName = "grid gap-6 xl:grid-cols-12 xl:auto-rows-[336px]"